apiVersion: v1
kind: Secret
metadata:
  name: tap-gui-techdocs-overlay
  namespace: tap-install
  annotations:
    package-to-overlay: "tap-gui"
type: Opaque
stringData:
  tap-gui-techdocs-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind": "Deployment", "metadata":{"name":"server","namespace":"tap-gui"}})
    ---
    spec:
      template:
        spec:
          containers:
          #@overlay/match by=overlay.subset({"name":"backstage"})
          - name: backstage
            #@overlay/match missing_ok=True
            env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375
            volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /output
              name: output
          #@overlay/append
          - command:
            - /bin/sh
            args:
            - -c
            - >-
                dockerd --host tcp://127.0.0.1:2375 &
                sleep 10 &&
                DOCKER_HOST=tcp://127.0.0.1:2375 docker pull TECHDOCS_IMAGE_PLACEHOLDER &&
                wait ${!}
            image: DIND_IMAGE_PLACEHOLDER
            imagePullPolicy: IfNotPresent
            name: dind-daemon
            resources: {}
            securityContext:
              privileged: true
              runAsUser: 0
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /output
              name: output
          #@overlay/match missing_ok=True
          volumes:
          - emptyDir: {}
            name: tmp
          - emptyDir: {}
            name: output