apiVersion: v1
kind: Secret
metadata:
  name: contour-ipv4-overlay
  namespace: tap-install
  annotations:
    package-to-overlay: "contour"
stringData:
  ipv4-overlay.yaml: |
   #@ load("@ytt:overlay", "overlay")
   #@overlay/match by=overlay.subset({"metadata":{"name":"contour"}, "kind": "Deployment"})
   ---
   spec:
     template:
       spec:
         containers:
           #@overlay/match by="name"
           - name: contour
             #@overlay/replace
             args:
             - serve
             - --incluster
             - '--xds-address=0.0.0.0'
             - --xds-port=8001
             - '--stats-address=0.0.0.0'
             - '--http-address=0.0.0.0'
             - '--envoy-service-http-address=0.0.0.0'
             - '--envoy-service-https-address=0.0.0.0'
             - '--health-address=0.0.0.0'
             - --contour-cafile=/certs/ca.crt
             - --contour-cert-file=/certs/tls.crt
             - --contour-key-file=/certs/tls.key
             - --config-path=/config/contour.yaml